name: kampuskita-db
services:
    postgres:
        restart: unless-stopped
        container_name: kampuskita-db
        environment:
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=kampus_data
        expose:
            - "5432"
        ports:
            - 3500:5432
        image: postgres:17.4-bookworm
